### ISSUE TITLE
Suggested enhancement

### ISSUE THREAD

**Issue by woodgieboodgie** [sfeakes/homebridge-sprinklerd#7]
Please add the sprinklers into the Status bar at the top of the page.  That way it'd be easy to see them on in line with the status of other device sin the home.

**Comment by sfeakes** [comment]
Can you please show a screen shot of what you mean, as I think what you are asking for is a home app setting.

**Comment by woodgieboodgie** [comment]
![status sprinklerd](https://user-images.githubusercontent.com/52473319/162542928-176c049a-22c3-4893-bdc8-39ef9cd3645a.jpg)

the setting is there but the status doesnt appear at the top of the page in Homekit.

was closed off previously: https://github.com/sfeakes/SprinklerD/issues/22

however my ipad and iphone cant see the staus on the page where the sprinklers are or on the favourites page.

**Comment by woodgieboodgie** [comment]
fixed with iOS update
